# Generated by Django 5.1.7 on 2025-04-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0002_alter_photo_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
    ]
