# Generated by Django 5.2 on 2025-04-21 08:39

import photoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0003_alter_folder_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=photoapp.models.upload_to_folder),
        ),
    ]
